 Vagrant.configure(2) do |config|
   config.vm.provider "virtualbox" do |v|
      v.memory = 4092
      v.cpus = 2
   end   
   config.vm.box = "centos/7"
   config.vm.hostname = "myhost"
   config.vm.network "private_network", ip: "192.168.50.10"
   config.vm.network "forwarded_port", guest: 9191, host: 9191
   config.vm.provision "shell", inline: <<-SHELL
      set -x
      sudo yum -y update
      sudo yum -y install java-1.8.0-openjdk
      sudo yum -y install htop
      sudo yum -y install git
      sudo mkdir -p /tern
      sudo chown vagrant:vagrant /tern
      cd /tern
      git clone https://github.com/tern-lang/tern-demo.git demo
      curl -O http://tern-lang.org/download/ternd-linux.tar.gz
      tar -xzvf ternd-linux.tar.gz
      nohup java -XX:+IgnoreUnrecognizedVMOptions --add-opens=java.base/jdk.internal.loader=ALL-UNNAMED -jar ternd.jar --server-only=true --directory=$PWD/demo --port=9191 > out.log &
   SHELL
 end
