 Vagrant.configure(2) do |config|
   config.vm.provider "virtualbox" do |v|
      v.memory = 4092
      v.cpus = 2
   end   
   config.vm.box = "centos/7"
   config.vm.hostname = "myhost"
   config.vm.network "private_network", ip: "192.168.50.10"
   config.vm.provision "shell", inline: <<-SHELL
      set -x
      sudo yum -y update
      sudo yum -y install java-1.8.0-openjdk
      sudo yum -y install htop
      sudo yum -y install git
      git clone https://github.com/tern-lang/tern-demo.git
      curl -O http://tern-lang.org/download/ternd-linux.tar.gz
      tar -xzvf ternd-linux.tar.gz
      java -jar ternd.jar --server-only=true --directory=$PWD/tern-demo --port=4457
   SHELL
 end
